### ISSUE TITLE
Business: Logo and top navigation don't appear

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#101]
On first activation, I think you'd expect to see those here.

Instead, it looks like this:

![screen shot 2015-12-14 at 9 55 30 am](https://cloud.githubusercontent.com/assets/376315/11777980/7e3a56dc-a249-11e5-8cbd-a4ff59fa143e.png)

**Comment by davidakennedy** [comment]
Should be fixed in our recent merge. See: https://github.com/Automattic/theme-components/commit/b4959efe5b97f317a8422203bbb1d58d57b0b928
