### ISSUE TITLE
Blog Modern: Generated theme has fatal error

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#107]
`Fatal error: Call to undefined function theme_traditional_posted_on() in /srv/www/wp-content/themes/vip/blog-modern/components/content/content.php on line 17`

This is an easy fix, but I'm not sure where to make it right now, given that the file structure is a bit in flux. I think it should be fixed by #102, and when I checked the `content.php` file in the pertinent branch, it looked like it was using an appropriate slug here.

**Comment by alaczek** [comment]
Fixed: https://github.com/davidakennedy/theme-components/commit/614aed052b7cc22fde133cc68a28a4966b04127d
