### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/theme-components#124]
The current readme.txt seems like it needs adjusting since it originally came from Underscores.

**Comment by sarahmonster** [comment]
Note: tags, if we decide to include them, should be consistent between this file and `style.scss`, which doesn't use any tags.

**Comment by davidakennedy** [comment]
When I worked on #141, I went ahead and made the `readme.txt` consistent with this change throughout all branches. My feeling is that it should be good to go for now. We can iterate further on the file once we ditch branches. Easier that way.
