### ISSUE TITLE
content-hero is blank

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#132]
This is super confusing when you generate a new theme. It definitely feels like there should be some skeleton content here.

https://github.com/Automattic/theme-pattern-library/blob/types/business/components/content-hero/content-hero.php

**Comment by alaczek** [comment]
I assume this one can be closed now?

**Comment by sarahmonster** [comment]
Blargh, this didn't automatically close the issue because the fix was merged into a non-master branch. :angry:
