### ISSUE TITLE
Wiki shouldn't include non-public links

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#157]
Instead of linking to pages that aren't publicly available, the wiki should have text filled out—even if it's copied verbatim from the original posts, that's better than references to posts most of the public can't read. 

Additionally, it would be great if we could expand these with other posts that are only available on an internal p2. Lots of good conversations about the direction of the project as well as its aims and scope have happened behind closed doors, and having this information publicly accessible and in one place means that potential contributors have a better understanding of the project and what we're trying to achieve. :)

**Comment by karmatosed** [comment]
I think I got them all.
