### ISSUE TITLE
Removing branches

### ISSUE THREAD

**Issue by karmatosed** [Automattic/theme-components#160]
This is a wide issue ticket but worth having up as we move onwards with things. Our goal is to remove the use of branches and use config files. This is going to take some movement but it will result in a more robust approach moving on. In order to do this, we are going to have to look at a lot of the structure as we go. Taking a 'measure twice, cut once' philosophy, we will plan this and make sure it's simple and not over engineered also.

**Comment by karmatosed** [comment]
Lets take this as an opportunity to clean up all the branches...

**Comment by davidakennedy** [comment]
We've officially removed branches here: https://github.com/Automattic/theme-components/commit/b4959efe5b97f317a8422203bbb1d58d57b0b928

More documentation on this is coming soon.
