### ISSUE TITLE
Question: what is our direction behind the componetisation of theme elements?

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#162]
I've worked on a few themes using Components, and it seems like the structure of the generated themes has changed over the past few months. I feel like it's worth clarifying what our aim is here and clearly stating what we're trying to achieve, since there may have been some miscommunication over this originally which has since compounded.

As an example, compare [Pique's components directory](/sarahmonster/pique/components) to this, which is what you get right now if you generate a theme using Components:
![screen shot 2016-02-04 at 12 31 27 pm](https://cloud.githubusercontent.com/assets/376315/12815010/4ab6fbba-cb3b-11e5-8913-ec7cd52cd5cc.png)

This super-fragmented approach may make generated themes pretty offputting to new users, particularly if they aren’t familiar with the background of the project and its end goals. That's okay if this is our intention, but if that isn't, in fact, our intention, we should try to fix it sooner rather than later. :smile: I wonder if users might be confused by what they get when they download a theme right now. It feels a bit counter-intuitive having some scss in assets, and some in components, and this is compounded by the aggressive folder structure—you end up with a bunch of tiny php files in individual folders, which feels a bit mentally taxing to work with (I've actually been copying code into different places and moving things around so it's easier for my brain to parse).

So: is our goal to have the source code (ie, the code in this repo) componentised, but the final generated themes look closer to _s in terms of structure? (ie, should the component elements be inserted into the theme files?) Or do we intend to have the generated themes fully componentised, so that theme developers would adopt a more piece-by-piece approach to theme design/development?

I believe there's been some confusion regarding our end goals for the project here, and I think it's important that everyone working on it is on the same page. Bringing more of these structural conversations to a public and canonical place will help us communicate the project to outside contributors, and also have a better canonical record for ourselves and other collaborators in the future.

**Comment by karmatosed** [comment]
@sarahmonster we talked about this in the meeting this week for Components, so let me summarise what will happen. They shouldn't stay when generated in the folders. The idea of the folders is for splitting multiples. I stand by their use in the repo. They were not intended to happen when the end output happened though. That wasn't ever an intention. 

As a result of this, let me close this because that will change once we review the generation.
