### ISSUE TITLE
Closing PHP tag in components/social-menu.php

### ISSUE THREAD

**Issue by michiecat** [Automattic/theme-components#182]
There was a closing PHP tag in components/social-menu.php that caused the WordPress.com VIP tests to complain when I committed it via SVN.

**Comment by deviodigital** [comment]
What was the error it was giving you? You're referencing [this file](https://github.com/Automattic/theme-components/blob/master/components/social-menu/social-menu.php) right?

**Comment by davidakennedy** [comment]
We've removed this file, in favor of Jetpack's social menu. See: https://github.com/Automattic/theme-components/blob/master/inc/jetpack.php#L28

We did this in a recent merge with lots of changes. See: https://github.com/Automattic/theme-components/commit/b4959efe5b97f317a8422203bbb1d58d57b0b928

**Comment by deviodigital** [comment]
:+1:
