### ISSUE TITLE
Modern Blog: jQuery undefined

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/theme-components#190]
In `main.js`:

`main.js?ver=20120206:149 Uncaught ReferenceError: jQuery is not defined`

**Comment by davidakennedy** [comment]
I can't seem to replicate this now, and have tried multiple page types. If it resurfaces, this issue can be reopened.

**Comment by alaczek** [comment]
Yep, I can reproduce too. We need to pass jQuery as dependency in `wp_enqueue_script` for this to work. On it! :)

**Comment by davidakennedy** [comment]
Fixed! Thanks @alaczek!
