### ISSUE TITLE
Business has wrong template part slug

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/theme-components#201]
template-front.php in the page-templates folder in the business theme has incorrect slugs:
`get_template_part( 'components/content', 'hero' );`
`get_template_part( 'components/testimonials' ); `

Should be:

`get_template_part( 'components/content-hero/content', 'hero' );`
`php get_template_part( 'components/testimonials/testimonials' ); `

I imagine the issue is bigger than just the business theme.

See: https://github.com/Automattic/theme-components/blob/types/business/page-templates/template-front.php

Reported by @rdswd here: https://github.com/Automattic/components.underscores.me/issues/108

**Comment by rdswd** [comment]
components/testimonials/testimonials.php is
`get_template_part( 'components/content', 'testimonial' );`
but should be:
`get_template_part( 'components/content-testimonial/content', 'testimonial' );`

**Comment by karmatosed** [comment]
I've fixed this in branchless-merge as this will be the main branch. It needed to be different because of structure changes coming.
