### ISSUE TITLE
Magazine theme has Front Page template assigned to index.php

### ISSUE THREAD

**Issue by rdswd** [Automattic/theme-components#202]
The magazine theme makes the index.php file a page template:
`/**
 * Template Name: Front Page
 *
 * @package second_mag
 */`

The conditional tag is_home is then used to show what I think the template is for but it is useless as is_home is for blog posts.
`		if ( is_home() ) {
			// Include the featured content template.
			get_template_part( 'components/featured' );
		}`
Perhaps the Front Page template is supposed to be in a page-templates folder with the is_front_page conditional and index.php is meant to keep the default usage plus the is_home conditional for featured content.

**Comment by karmatosed** [comment]
This is meant to just be index.php and has been corrected in the branchless-merge, which will be root soon.
