### ISSUE TITLE
Strict comparision for `get_post_type` in template files

### ISSUE THREAD

**Issue by ernilambar** [Automattic/theme-components#207]
Currently there is `'post' == get_post_type()`. It'd better if we use strict comparision. like `'post' === get_post_type()`

**Comment by davidakennedy** [comment]
Thanks for the the issue! We fixed this in a recent merge with lots of changes. See: https://github.com/Automattic/theme-components/commit/b4959efe5b97f317a8422203bbb1d58d57b0b928
