### ISSUE TITLE
Wrong slug defined for top menu location

### ISSUE THREAD

**Issue by adiacone** [Automattic/theme-components#212]
The top menu doesn't work, because the location is registered using the 'top-menu' slug, but in _components/top-navigation/top-navigation.php_ `wp_nav_menu` is called using the 'top' slug.

**Comment by WPDevHQ** [comment]
Already submited a pull request on this - [#205 ](https://github.com/Automattic/theme-components/pull/205)

**Comment by karmatosed** [comment]
Thanks for this, we've fixed in a branch that will be the main branch once we're done with next phase.
