### ISSUE TITLE
Search form component isn't used by themes

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#213]
I noticed that we've included a `search-form.php` file in Components. This file isn't being used at all by generated themes and should probably be removed, unless there are specific plans for it.

I was under the impression it's bad practise to override the core search form output. Additionally, the output provided by the current search-form.php file is exactly the same as the core output when using the HTML5 option (already set in theme support). 

If we still want to include this file, it should be renamed to `searchform.php` so that it will be used by the generated themes.

**Comment by kevinmamaqi** [comment]
In addition, when search-form.php from the main folder is renamed to searchform.php doesn't work.

**Comment by karmatosed** [comment]
I'm killing this in latest update to simplify. You can see this removed in branchless-merge which will become main branch once we kill branches. What a sentence to confuse!
