### ISSUE TITLE
Alternate word to 'components' folder

### ISSUE THREAD

**Issue by lukewhitehouse** [Automattic/theme-components#215]
This could be confusing for people using [bower](http://bower.io/) in their projects and I know a lot of people change their `bower_components` folder to simply `components`.

**Comment by karmatosed** [comment]
For us we want to keep to components as that's what it is. I totally get you may want to use bower but not everyone will. There are a lot of different projects and systems people use. We can't really cater for all. Components also has meaning in the world of React and at it's heart simply means 'small elements'. For this project it's right as a result.
