### ISSUE TITLE
Jetpack Social Menu fallback

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/theme-components#217]
I ​would *highly*​ recommend removing the fallback.
The fallback is meant for old themes that are already supporting a social menu.
Components should only focus on Jetpack otherwise using JSP is almost pointless if we have to include all the CSS and menu registration for the fallback again.

**Comment by karmatosed** [comment]
I've removed fallback and updated all types to have JetPack social menus included in the latest branch we're moving to during meetup.
