### ISSUE TITLE
Blog Modern: Site title and description only show with header image is added

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/theme-components#259]
See: https://github.com/Automattic/theme-components/blob/branchless-merge/components/header/header-fullscreen-image.php

Because of the `<?php if ( get_header_image() ) : ?>`, the site title and description don't show in all cases, and the theme type seems broken. I'd suggest we refactor this code to be a bit less opinionated when it comes to the site title and description and have it show always.

**Comment by davidakennedy** [comment]
cc: @karmatosed for some thoughts here since you had the original vision for this type.

**Comment by karmatosed** [comment]
I agree we should refactor.

**Comment by sixhours** [comment]
This appears to have been fixed in the latest version; a downloaded Blog Modern theme shows the site title and tagline even when no header image is present, and the code for that piece has already been refactored.

Closing this.
