### ISSUE TITLE
Add content to contribution doc on wiki

### ISSUE THREAD

**Issue by karmatosed** [Automattic/theme-components#263]

**Comment by davidakennedy** [comment]
I've made edits and organizational changes to the wiki: https://github.com/Automattic/theme-components/wiki/

* I consolidated a few pages by folding them into the main page.
* Also added numbers to the titles so things order nicely, and drop people into a table of contents view.
* Fleshed out a types page: https://github.com/Automattic/theme-components/wiki/2.-Types

I'm calling this done – for now. 😄
