### ISSUE TITLE
Blog classic: adding widgets doesn't make sidebar appear to side

### ISSUE THREAD

**Issue by karmatosed** [Automattic/theme-components#267]
The sidebar is meant to go to the side, however it doesn't, you just get the sidebar appear below the content. This isn't great as not the layout we were trying to go for with blog classic.

**Comment by karmatosed** [comment]
After poking around, I think this could be due to:

`// @import "content-sidebar";
// @import "sidebar-content";`

**Comment by alaczek** [comment]
Looking at the config files, only the Blog classic even includes _content-sidebar.scss, so I'm wondering if we should keep the other layout. 

I'm also wondering, if this isn't a generator issue? When config includes one of the layouts, corresponding `@import` line in `_layout.scss` should probably be uncommented, and the other one (the include for the other layout) should not be there at all.

**Comment by sixhours** [comment]
Partially addressed this in #273

**Comment by davidakennedy** [comment]
I tested this, and it's working.

I think this issue can be safely closed. Figuring out how to more intelligently handle layouts is another issue we should figure out separately.

Filed issue here: https://github.com/Automattic/components.underscores.me/issues/152
