### ISSUE TITLE
Recommended bundling of third party assets?

### ISSUE THREAD

**Issue by vmasto** [Automattic/theme-components#271]
Just looking for opinions on what would the recommended practice/folder structure would be for bundling and using third party assets (i.e. FontAwesome, some jQuery plugin with scripts and styles, etc).

Perhaps a `/vendor` directory within `/assets`, and if so, should the whole plugin repo be included as it is fetched or just pick the relevant files out of it? Any thoughts?

**Comment by karmatosed** [comment]
We currently have no suggested practice as we're leaving it up to each developer for theme side. Everyone has their own working methods and we really want to encourage that.
