### ISSUE TITLE
Modern blog: featured image on single posts and pages

### ISSUE THREAD

**Issue by karmatosed** [Automattic/theme-components#289]
The featured image showing in the header should happen for single posts and pages.

**Comment by sixhours** [comment]
I think we need to punt this 'til the next iteration. There's some decision-making that has to happen as to how we do it.

**Comment by davidakennedy** [comment]
Some of that decision making is around implementation:

I’d like to be consistent. I think the current custom header inserts the image into the HTML with an `img` tag. But some theme designs are better inserting the image via CSS as a background.

I’m wondering if we should standardize this in some way in Components? Or have a way to say, “Do it this way when… and that way when…

Thoughts?

**Comment by karmatosed** [comment]
Closing this as we are merging the blog types.
