### ISSUE TITLE
Make magazine type have three columns

### ISSUE THREAD

**Issue by sixhours** [Automattic/theme-components#66]
Something that I often struggle with in creating a magazine-style layout is the cleanest CSS for three columns.

We used to have CSS for this in the _s layouts folder (sidebar sidebar content, sidebar content sidebar, content sidebar sidebar) but removed it.

The Magazine type in particular seems suited to three columns, so maybe this could be a pattern.

**Comment by karmatosed** [comment]
I like that idea. Magazine I struggled with making different - in the end it's just a two column with the featured on top. Lets add that in and make this a different pattern as a result. We can always use the two column if wanting a more traditional layout. I like idea we make magazine different. You are right, a lot of magazines have 3 column. We could even make the 3rd optional with 'if have widgets'.
