### ISSUE TITLE
Re-brand to match user-facing site

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/theme-components#91]
I've been thinking about our copy and branding on the Components site and I'm concerned we may end up with some user confusion. 

As it stands right now, "Components" is a custom starter theme you can download from components.underscores.me. To contribute to "Components", you need to visit this repo—currently referred to throughout as "theme pattern library". 

Essentially, the issue is that we have one repo—this one—that doesn't have any reference to "Components", and the Components site/generator, that doesn't have any reference to the theme pattern library. The theme slug used throughout the pattern library files (and resulting generated themes) is `component_s`. There isn't any consistent naming pattern.
.
This is particularly obvious when working on https://github.com/Automattic/components.underscores.me/issues/11. Given that we want to encourage contributions as much as possible, it's important that we make sure it's very clear which repo does what. Documentation will help with this (I'll open some related PRs for this), but clear and matching names will go a long way. 

I'd suggest renaming this repo to something simple, understandable, and in-line with the public-facing site:

* Theme Components
* Component Library

...and then changing the theme slug used throughout to match.

**Comment by sixhours** [comment]
I vote Theme Components.

**Comment by karmatosed** [comment]
I think they are patterns but happy to go with the consensus.

**Comment by karmatosed** [comment]
Unless I'm mistaken, this has now happened.

**Comment by sarahmonster** [comment]
Will be closed fully by #156 above—there are still pattern library references in README and contributor docs. :smile:

**Comment by karmatosed** [comment]
Doh sorry about that.

**Comment by karmatosed** [comment]
I should have caught everything now - let me know if didn't.
